// Generated by CoffeeScript 1.6.3
var Input;

Input = {
  setup: function() {
    game.input.keyboard.on(gf.Keyboard.KEY.W, Input.up);
    game.input.keyboard.on(gf.Keyboard.KEY.S, Input.down);
    game.input.keyboard.on(gf.Keyboard.KEY.A, Input.left);
    return game.input.keyboard.on(gf.Keyboard.KEY.D, Input.right);
  },
  up: function(e) {
    return false;
  }
};
