// Generated by CoffeeScript 1.6.3
var Input;

Input = {
  setup: function() {
    game.input.keyboard.on(gf.Keyboard.KEY.W, Input.up);
    game.input.keyboard.on(gf.Keyboard.KEY.S, Input.down);
    game.input.keyboard.on(gf.Keyboard.KEY.A, Input.left);
    return game.input.keyboard.on(gf.Keyboard.KEY.D, Input.right);
  },
  up: function(e) {
    return Input.doMove('n', e.down);
  },
  down: function(e) {
    return Input.doMove('s', e.down);
  },
  left: function(e) {
    return Input.doMove('w', e.down);
  },
  right: function(e) {
    return Input.doMove('e', e.down);
  },
  doMove: function(direction, keyDown) {
    var c;
    c = Characters.store['player'];
    if (keyDown) {
      switch (direction) {
        case "n":
          c.setVelocity(0, c.movespeed);
          break;
        case "s":
          c.setVelocity(0, -c.movespeed);
          break;
        case "e":
          c.setVelocity(c.movespeed, 0);
          break;
        case "w":
          c.setVelocity(-c.movespeed, 0);
      }
      if (c.direction === false) {
        c.goto(1, direction).play();
      }
      return c.direction = direction;
    } else {
      c.direction = false;
      return c.goto(1, direction).stop();
    }
  }
};
