// Generated by CoffeeScript 1.7.1
var Map;

Map = {
  tileClick: function(e) {
    var tile;
    tile = e.target;
    tile.hitArea = new gf.Rectangle(-32, -32, 64, 64);
    tile.mass = Infinity;
    tile.enablePhysics(game.physics);
    tile.alpha = 0.5;
    return console.log(tile);
  }
};
