// Generated by CoffeeScript 1.6.3
$(window).ready(function() {
  var game;
  game = new gf.Game('game', {
    width: window.innerWidth,
    height: window.innerHeight,
    background: 0x000000,
    interactive: true
  });
  game.loader.on('complete', function() {
    game.loadWorld('island2');
    return game.render();
  });
  game.loader.on('progress', function(e) {
    return false;
  });
  return game.loader.load([
    {
      name: 'island2',
      src: 'resources/map/island2.json'
    }
  ]);
});
